### ISSUE TITLE
Bucket duplication.

### ISSUE THREAD

**Issue by SwanX1** [TelepathicGrunt/Bumblezone#10]
If you take a water bucket and craft it together with sugar, you get a bucket of sugar water, but the original bucket stays in the crafting table. Thus the original bucket is now duplicated.

**Comment by TelepathicGrunt** [comment]
I see they issue. It's due to how crafting tables treat recipes with contain items like buckets differently. this is annoying lol.

I might be able to create a special recipe thing for it but it may be more work than it's worth. For now, you could either use a datapack to disable the recipe or add an empty bucket to it so it's 1 bucket + 1 water bucket + sugar -> bucket + sugar water bucket.

**Comment by TelepathicGrunt** [comment]
Thank you for reporting this bug! I was able to add a special recipe handler for the sugar water recipe. v1.3.7 now has the patch and is released. :)
