### ISSUE TITLE
Mod Compatability - Silent's Gems 3

### ISSUE THREAD

**Issue by sstarr82** [TelepathicGrunt/Bumblezone#111]
Please add a token recipe for comb cutter so it can be crafted with the token enchanter.
The token already exists, so it just needs a crafting recipe.

**Comment by TelepathicGrunt** [comment]
what's a token recipe? or even token enchanter?

**Comment by sstarr82** [comment]
> what's a token recipe? or even token enchanter?

It is a way to add/create enchantments without guesswork, here's a link to the mod on curseforge 
https://www.curseforge.com/minecraft/mc-mods/silents-gems

**Comment by TelepathicGrunt** [comment]
Token Enchanter is not out for 1.18.2 yet as the 1.18.1 version will not run on 1.18.2. When it is out for 1.18.2, then I'll release my Bumblezone update for that mc version to have the recipe files for tokens. You can try this datapack for 1.18.1 Bumblezone since I will not be updating older versions of my mod anymore. let me know if these tokens feel balanced or not if you're playing on 1.18.1 so I know what to adjust in 1.18.2 update
[bumblezone_token.zip](https://github.com/TelepathicGrunt/Bumblezone/files/8404678/bumblezone_token.zip)

**Comment by sstarr82** [comment]
Perfect thank you!
