### ISSUE TITLE
Crashes after recent Update 6.2.5

### ISSUE THREAD

**Issue by Zelioth** [TelepathicGrunt/Bumblezone#138]
Minecraft Version - 1.19.2
Forge Version - 43.1.25
Mod Version - 1.0.0 -1.19.2

Custom Mod Pack and Server : https://www.curseforge.com/minecraft/modpacks/friends-united

I've used the mod in my pack for some time now. Love it. Had some issues but we have gotten past them. Recently after updating the mods and pack yesterday we are now experiencing crashes that are referencing to two mods and one is "The Bumble Zone" and the other is "Takes A Pillage" I hope these reports help. I will post them all. 

I do not know how to recreate the issue. It just happens. Players are saying they aren't interacting with Bees or anything so im unsure. One player is also saying they are getting "Internal Server Error" when they attempt to drink honey now as well. 

[crash-2022-09-15_10.22.02-server.txt](https://github.com/TelepathicGrunt/Bumblezone/files/9576480/crash-2022-09-15_10.22.02-server.txt)
[crash-2022-09-15_12.06.50-server.txt](https://github.com/TelepathicGrunt/Bumblezone/files/9576481/crash-2022-09-15_12.06.50-server.txt)
[crash-2022-09-15_12.34.15-server.txt](https://github.com/TelepathicGrunt/Bumblezone/files/9576482/crash-2022-09-15_12.34.15-server.txt)

**Comment by TelepathicGrunt** [comment]
Just documenting our findings here as well. The crash was caused by It Takes A Pillage mod missing a null check in a forge event for status effect removals and was causing that mod to crash even with vanilla’s items. Bumblezone has some status effect removals that triggered this bug in It Takes A Pilalge.

That mod has now updated to fix that crash so this issue report will be closed.
