### ISSUE TITLE
1.19.2 crash/force close after update 6.4.0

### ISSUE THREAD

**Issue by fixthissitepls** [TelepathicGrunt/Bumblezone#162]
So the problem is that the game doesn't really “crash” the game rather tries to load, but the launcher just doesn't even let me in the game and just throws out the generic "exit code 1" after a few seconds.
That means i dont have a crash log, i could send the launcher log if that helps,altough it does not say that much.

**Comment by TelepathicGrunt** [comment]
Please make sure you’re on latest forge version (if you’re on forge) and please give me the latest.log file after the issue occurs. The latest.log file can be found in the logs folder above the mods folder

**Comment by fixthissitepls** [comment]
I am using forge version 43.1.47
[latest.log](https://github.com/TelepathicGrunt/Bumblezone/files/10014222/latest.log)

Updating to the newest forge version makes my game close the same way even without this mod installed at all, so i dont know whats going on here

**Comment by TelepathicGrunt** [comment]
The log you showed says you were running forge 43.1.47 when 43.1.52 is required by Bumblezone due to me using a new event introduced then. Why forge isn’t showing the dependency screen, idk as that might be a forge bug.

[15Nov.2022 16:56:13.961] [main/INFO] [net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator/]: Found 8 dependencies adding them to mods collection
[15Nov.2022 16:56:14.045] [main/ERROR] [net.minecraftforge.fml.loading.ModSorter/LOADING]: Missing or unsupported mandatory dependencies:
	Mod ID: 'forge', Requested by: 'the_bumblezone', Expected range: '[43.1.52,)', Actual version: '43.1.47'

Now after updating the new forge version, try again and give the latest.log for that forge version if it still has issues

**Comment by fixthissitepls** [comment]
thank you, here is the log after updating to the newest version.
[latest.log](https://github.com/TelepathicGrunt/Bumblezone/files/10014286/latest.log)

**Comment by fixthissitepls** [comment]
Ok after some further testing I found out that some other mod was causing the issue thank you for your help.

**Comment by TelepathicGrunt** [comment]
Ah glad you were able to resolve it! I'll make an issue report to forge for why their dependency screen is not showing up as that is going to make it harder for users
