### ISSUE TITLE
bee armor crashing bug

### ISSUE THREAD

**Issue by TheG0dC0der** [TelepathicGrunt/Bumblezone#180]
whenever I go into f5 or my inventory with the bee armor on my game crashes
![image](https://user-images.githubusercontent.com/106412145/209499298-b76fbbd3-178f-4c2c-ab7d-24a5db95fdfb.png)

this is on the medieval MC fabric 1.19.2 v14.5 modpack

edit: specifically the bee helmet I put on(it was the half one)

edit2: I think I came up with a idea, by opening a container I can empty my inventory without loading the player preview and after all valuables are emptied I can /clear and hopefully remove the vanilla armor, fixing the conflict that resulted in a nil value

edit3: for anyone who has the same problem and finds this /clear works and will not clear any of your trinkets, dying would also probably work but medieval MC has graves so dying is not a workable solution

**Comment by TelepathicGrunt** [comment]
Not a Bumblezone issue. Disable Cosmetic Armors for now or avoid filling up your cosmetic armor slots with any modded armor at the moment until the issue is resolved on Immersive Armor and Better End's side. Update Geckolib to latest version as they fixed their mixin to run earlier and stop their crash with Cosmetic Armor.

See this person's explanation of the issue. https://github.com/emilyploszaj/trinkets/issues/228#issuecomment-1352587455

Better End's issue report: https://github.com/quiqueck/BetterEnd/issues/129

Immersive Armor's report which the dev is currently working on a fix at the moment: https://github.com/Luke100000/ImmersiveArmors/issues/65

Nothing on my end that I can do as this is a multi-mod interaction due to needing to render armor from extra armor slots added by another mod

**Comment by TheG0dC0der** [comment]
alright thank you, I thought the cosmetic armor slots just used the same code or something for rendering normal armor,(not deep with knowledge on this subject)

edit: how would I fix this then, aka how would I take the armor off if I can't get into my inventory

edit2: I think I came up with a idea, by opening a container I can empty my inventory without loading the player preview and after all valuables are emptied I can /clear and hopefully remove the vanilla armor, fixing the conflict that resulted in a nil value

edit3: for anyone who has the same problem and finds this /clear works and will not clear any of your trinkets, dying would also probably work but medieval MC has graves so dying is not a workable solution

**Comment by TelepathicGrunt** [comment]
Haven't heard anything recently about Cosmetic Armor crashing anymore so this might finally stopped being an issue. Closing
