### ISSUE TITLE
The dimension name bug

### ISSUE THREAD

**Issue by Mikeliro** [TelepathicGrunt/Bumblezone#19]
In all versions
The dimension name looks like 'the_bumblezone.the_bumblezone' instead of 'The Bumblezone'

**Comment by TelepathicGrunt** [comment]
May I ask where you are specifically seeing "the_bumblezone.the_bumblezone"?

To me, the dimension name should be "the_bumblezone/the_bumblezone" as shown here and there's no way to actually see the name of the dimension itself. Even vanilla's en_us.json file has no entry for their dimension names. Just to be clear, the dimension name is made of two parts. The first part is the mod ID which is "the_bumblezone" or "minecraft". Then the second part is the actual name of the dimension which is "the_bumblezone" or "the_nether". That's why "the_bumblezone/the_bumblezone" is correct.
![image](https://user-images.githubusercontent.com/40846040/92471317-be21b780-f1a5-11ea-846f-a3ad6dee55b1.png)

But I haven't seen "the_bumblezone.the_bumblezone" with a period which is why I am asking where you are seeing that as that's super odd

**Comment by Mikeliro** [comment]
In mods that request the name of the dimension where you are.
The vanilla dimensions appear with the respective names: Overworld, The End and Nether.
But the dimension 'The Bumblezone', appears as 'the_bumblezone.the_bumblezone'.

**Comment by TelepathicGrunt** [comment]
Can you give me a name of those mods you were using for that? I think they may had handled vanilla dimensions themselves but I can see if they have a way for me to say what The Bumblezone should be called.

**Comment by Mikeliro** [comment]
Corpse by henkelmax: https://www.curseforge.com/minecraft/mc-mods/corpse
GraveStone Mod by henkelmax: https://www.curseforge.com/minecraft/mc-mods/gravestone-mod

**Comment by TelepathicGrunt** [comment]
Ok so with Gravestone, the dimension names are done through their config file. Try finding their config file and you should be able to add an entry for The Bumblezone to make it look nicer. 
https://github.com/henkelmax/gravestone/blob/b286e1d0c413ed841d5e083dc5682aeaa8477dd2/src/main/java/de/maxhenkel/gravestone/ClientConfig.java#L30

I'm still looking into Corpse to see how they do it. For the looks of their code, it looks like they only show the right side of the modid:dimension_name format so their's should be showing "the_nether" and "the_bumblezone". Hmm. Gonna try it in-game to see
https://github.com/henkelmax/corpse/blob/7ef4251e583b7dccb7d0fd4b17f4f43f2e8fbb4c/src/main/java/de/maxhenkel/corpse/gui/DeathHistoryScreen.java#L120-L121

**Comment by TelepathicGrunt** [comment]
Yeah corpse is showing the bumblezone's dimension name the way they wanted it to as "the_bumblezone". The Nether is shown as "the_nether".

![image](https://user-images.githubusercontent.com/40846040/92516616-76218580-f1e3-11ea-890a-789fd6762b14.png)

![image](https://user-images.githubusercontent.com/40846040/92516608-71f56800-f1e3-11ea-8cee-4316f5e67b5f.png)

But thank you for bringing this up! I'll keep an eye out for other mods that uses dimension names and see if they are working or if they expect other dimension mods to hook into their mod to specify names. A big reason why it seems everyone is doing their own way to get dimension names is because Mojang never added vanilla dimension names to the en_us.js file so there's no standardized way of getting dimension names. 

I'll close this for now but if you got another mod that is having trouble with dimension names and does not have a config for them, just reply here and I'll look at it.
