### ISSUE TITLE
1.19.3 Bumblezone latest version 6.6.2 failing to load with Productive Bees - missing registry

### ISSUE THREAD

**Issue by PiDay314** [TelepathicGrunt/Bumblezone#202]
Hello!

I'm trying to use the latest version of The Bumblezone on 1.19.3... It never even pulls up the Minecraft loading screen, it just crashes straight back to the launcher.

I tried both Forge 44.1.0 ("recommended" on Forge's website) as well as the newest one, 44.1.8.  

Both of them appear to have thrown up the same error.  From what I could read, it has to do with missing registries?  I removed The Bumblezone from my mod list and it ran just fine on 44.1.8, so it definitely appears to be something with the mod.  I know Forge tends to break registries periodically, so I'm wondering if that is the issue here... although it's a bit odd that only this one was affected out of my 60+ mods.

[crash-2023-01-28_23.06.35-client.txt](https://github.com/TelepathicGrunt/Bumblezone/files/10531397/crash-2023-01-28_23.06.35-client.txt)
[crash-2023-01-28_23.15.50-client.txt](https://github.com/TelepathicGrunt/Bumblezone/files/10531398/crash-2023-01-28_23.15.50-client.txt)

**Comment by TelepathicGrunt** [comment]
it's not forge. it's the code for compat with productive bees. I need to redo the compat entirely due to changes in 1.19.3 vanilla worldgen registries. I never tested this compat beforehand for 1.19.3 because productive bees was not yet out for 1.19.3. 

There is no workaround. Either remove bumblezone or productive bees until i put out a fixed version of bumblezone

**Comment by TelepathicGrunt** [comment]
fixed now in 6.6.3 releases for 1.19.3
