### ISSUE TITLE
Beeheemoth Suggestion

### ISSUE THREAD

**Issue by GroggMayles** [TelepathicGrunt/Bumblezone#221]
Hello !
I was wondering if there is any particular reason I cant "pick up " my tamed Beeheemoth using Kibe Lassos. The only mobs I havent been able to pick up are world bosses and what not, which is understandable. I hope that by Beelieving in this suggestion hard enough, my dream just might come true

Thanks !

**Comment by TelepathicGrunt** [comment]
Beehemoth has a ton of interaction checks to make removing saddle when empty handed right click, ride when not empty, etc. lasso’s code may be trying to run afterwards but the riding code takes precedence. I can try and look into explicitly allowing their item’s use to go through when used on beehemoth. 

Though you can ride or honey bucket lure the beehemoth anywhere you need for now

**Comment by TelepathicGrunt** [comment]
Looks like their lasso is working just fine for me in 1.19.2 fabric
https://user-images.githubusercontent.com/40846040/225369932-a3159e3a-af02-41a9-90f5-e4a6cfb5e416.mp4

**Comment by TelepathicGrunt** [comment]
Yeah tested in my own dimension and Golden/Diamond Kibe Utilities Lassos are able to pick up untamed, tamed, and saddled Beehemoths in 1.19.2+. Going to close this as there doesn't seem to be any issue here.

If you are using 1.18.2 or older Bumblezone, I am no longer supporting those mc versions. Otherwise, there might be another mod interfering but you'll have to hunt that down in your modpack
