### ISSUE TITLE
Compatibility - Crystalline Flower Dupe with CarryOn mod [Fabric]

### ISSUE THREAD

**Issue by muon-rw** [TelepathicGrunt/Bumblezone#239]
1. Pick up a crystalline_flower[flower=false] with CarryOn
2. A [flower=true] with the flower's XP level gets placed into the player's hands
3. A [flower=true] with the flower's XP level also drops as an item, duplicating both the flower and the XP. 

I haven't tested if the issue persists in the Forge version of both mods. 

Is this something to be resolved on Bumblezone's end, or does the block just need to be blacklisted? 

Versions:
Carryon-fabric-1.19.2-2.0.4.6
the_bumblezone_fabric-6.7.9+1.19.2
Fabric 0.14.19

**Comment by TelepathicGrunt** [comment]
Blacklist it as it doesn’t make sense to even have carryon interact with the flower since the flower always drops itself when broken by any method and can only be placed on crystal-like blocks. Feels like it would be more problematic and clunky for users to have carry on be the thing that picks up the block. 

I’ll see if there’s a way to have that mod skip my block always

**Comment by TelepathicGrunt** [comment]
They have a tag blacklist but it doesn't appear to be working. I did let the dev know so hopefully they will release a fix soon for that

**Comment by TelepathicGrunt** [comment]
Carry On just updated and I'm assuming they fixed their config so should be all good now. Bumblezone also now includes a tag entry to add Crystalline Flower to their blacklist tag automatically out of the box
