### ISSUE TITLE
Recommendation (Quilt exclusive due to mod): Effective splash effect in sugar water 

### ISSUE THREAD

**Issue by Shibva** [TelepathicGrunt/Bumblezone#246]
see https://github.com/Ladysnake/Effective/issues/178

**Comment by TelepathicGrunt** [comment]
This doesn’t look reasonable to do on my end. Effective does quite a few mixins to vanilla water which I rather not recreate entirely for my own mod. Rather it would be better if they make their compat use a config or fluid tag or something to specify what fluids it works for and make their mixins for general fluids instead of to vanilla water class
