### ISSUE TITLE
Bug - Cannot find tags & BZ Pollination File Reading Error & Can't parse pollen puff entity to flower

### ISSUE THREAD

**Issue by Yourname942** [TelepathicGrunt/Bumblezone#249]
**Description**
A) Cannot load tag
B) BZ Pollination File Reading Error
C) Couldn't parse pollen puff entity to flower

**Steps to Reproduce**
1. Open Curseforge app
2. Create a new profile
3. MC 1.19.2
4. Forge 43.2.11
5. Install JEI 1.4
6. Install Bumblezone 6.7.14
7. Install Born in Chaos 1.4
8. Install geckolib3.1.39
9. launch the game
10. create a new world (creative/hard)
11. enter the world
12. close the game
_observe the errors in the log file_

**Latest log:** https://paste.ee/p/MT3tW

**Comment by TelepathicGrunt** [comment]
I do not get that when running Bumblezone fresh myself and all the tags and files do exist. This seems more like this forge issue where forge logspams about worldgen tags but was magically fixed in 1.19.3+. Nothing I can do about it as it is a Forge issue. https://github.com/MinecraftForge/MinecraftForge/issues/8771
 
 The tags still work and exist in game so no issue there. 
 
 The born in chaos pollen puff entry you can ignore. That was me just putting in an entry for one of their mobs in case they fix the registry name for it as they mispelled sir as ser. It won't break the file. It was just future proofing but will log it's failure to find the mob. That's all. No issue there either.
