### ISSUE TITLE
Bumblezone Incompatible with Resourcefullbee's mod

### ISSUE THREAD

**Issue by Rory0merchury** [TelepathicGrunt/Bumblezone#25]
minecraft crashes on launch whenever bumblezone and resourcefullbee's mod is installed.
took me 2 days to pinpoint it in my WIP modpack.

see hastebin for more info:
Hastebin: https://haste.romvoid.dev/nibugaxide.yaml

mcver 1.16.3 with latest forge .25

**Comment by TelepathicGrunt** [comment]
I need more info of what you mean. What minecraft version? Latest Forge version and latest version of both those mods? What is happening that shows they are incompatible?

**Comment by Rory0merchury** [comment]
> I need more info of what you mean. What minecraft version? Latest Forge version and latest version of both those mods? What is happening that shows they are incompatible?

updated main post accidentally posted enter when creating this issue

**Comment by TelepathicGrunt** [comment]
Looks like our coremods might be conflicting. I'll check it out when I get a chance

**Comment by Rory0merchury** [comment]
Mod versions: the bumblezone [2.1.1] and resourcefullbee's ver [1.16.3-0.5.4b]

**Comment by TelepathicGrunt** [comment]
Found it. It is my BeeEntityInvoker mixin conflicting in Resourceful Bees's AT. Will try and apply a fix for that. Thank you for reaching out to me about this!

**Comment by TelepathicGrunt** [comment]
2.2.0 is now out and fixes the crash! In fact, I went ahead and add mod compatibility directly with Resourceful Bees as well!

**Comment by bessiq** [comment]
Not sure that Resourceful Bees got the memo, because running both mods together causes a crash during early loading. Tried RBees 0.5.4b and 0.5.5b on Forge 34.1.25. Game loads fine with one or the other enabled, just not both.

I've been trying to use RBees off and on since 1.15.2, and I just have not had very good luck with it. I mean Productive Bees is still not registering features correctly (only when Bumblezone is present fwiw), but at least the game loads. 😕 

log: https://gist.github.com/bessiq/c403678ec6ee9644921ede937f75d74e

**Comment by TelepathicGrunt** [comment]
Hmm. I'll check this out once the forge breaking change is taken care of for my mod and theirs

**Comment by TelepathicGrunt** [comment]
v2.2.1 is out and should fix this! I was using Resourceful Bees v0.5.5b in my testing so update them too if you haven't. Let me know if issues persist!

**Comment by NovaNeon4** [comment]
I believe the issue is still ongoing, I just installed resourceful bees and tried to enter the dimension to no avail. My game froze and then crashed. Here's the log:
[latest.log](https://github.com/TelepathicGrunt/Bumblezone/files/5473548/latest.log)

**Comment by TelepathicGrunt** [comment]
That log shows an issue with Bumblezone/Productive bees. Not resourcefulbees
It seems I mistyped this check that should be productive bees instead of potion of bees. Thank you for letting me know!
https://github.com/TelepathicGrunt/Bumblezone/blob/03ea5a4d11779bab0c346dd57558a96da15afce2/src/main/java/com/telepathicgrunt/the_bumblezone/features/SpiderInfestedBeeDungeon.java#L366

**Comment by TelepathicGrunt** [comment]
v2.2.2 is out and should fix the bug where having potion of bees on and productive bees off causes a crash.
