### ISSUE TITLE
Question: Quilt Exclusive releases? why?

### ISSUE THREAD

**Issue by Shibva** [TelepathicGrunt/Bumblezone#252]
Tbh im curious on why the mod has a quilt release of the mod;

I'm aware that this may seem necessary to some people but the thing is Quilt API libraries is a fork on the fabric's API library and is kept to be as similar as possible to allow for fabric mods to be compatible with quilt-loaders API 

So I do ask: why do ya have a quilt version? tbh, I'm just asking because at this point im genuinely curious about the reasoning. 

(this curiosity may be due to the fact I have run into zero issues when playing on the fabric release on quilt-loader with its quiltloaderAPI)

**Comment by TelepathicGrunt** [comment]
because the setup I have with arch makes it not that much effort to support exclusively in case quilt has api stuff that fabric ends up not having. Also easier to test quilt if quilt is running in dev environment and at that point, might as well release the quilt jar. You can make your mod only for fabric and let quilt load it on its own

**Comment by Shibva** [comment]
I see, well the whole purpose of quilt was to be an alternate splitter of farbic while still having backwards compat but I see your point

thanks for quick response ^w^
