### ISSUE TITLE
[1.18.2] Server crash upon trying to join world

### ISSUE THREAD

**Issue by Proxwian** [TelepathicGrunt/Bumblezone#253]
Happens when player thrown eye into beehive. I know you don't update 1.18.2 version, but any chance I can fix it by myself?

[crash-2023-06-09_13.08.32-server.txt](https://github.com/TelepathicGrunt/Bumblezone/files/11706610/crash-2023-06-09_13.08.32-server.txt)

**Comment by TelepathicGrunt** [comment]
>   Running: Magma version git-Magma-1.18.2-1dbff192 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) false

Yeah you cannot run mods with these plugin/mod hybrids. They are usually fundamentally broken when running larger content mods like Bumblezone. 

Specifically, Magma broke Forge Capabilities. These are pieces of data that Forge allows modders to attach to entities and stuff to keep track of stuff or do stuff. All entities should have the capability attach to them. The fact that your character did not have the Capability on them when teleporting to Bumblezone means Magma is fundamentally broken and failed to reimplement Forge properly. 
https://github.com/TelepathicGrunt/Bumblezone/blob/b4b0822c8255eea0a9311b9e1667c1bc59c170c1/src/main/java/com/telepathicgrunt/the_bumblezone/world/dimension/BzWorldSavedData.java#L106

Your best bet is to either bug report to Magma or just remove it entirely and run a strictly Forge only server with no plugins.

**Comment by Proxwian** [comment]
@TelepathicGrunt issue was in mod RestrictedDimensions, not in magma. Just be more flexible.

**Comment by TelepathicGrunt** [comment]
@Proxwian 
> Just be more flexible.

No as mods and plugins are not made to work together. Each were entirely designed in their own ecosystem with no regards to the existence of the other. Many other modders I talk to all despise every plugin/mod hybrid because all of them are broken on a fundamental level in some way and causes the weirdest bug reports for us as there's no way to have both Forge and Bukkit both be implemented perfectly in their entirety without something breaking the other or the mods and plugins conflicting or the hybrid creators just straight up missing an API feature/implementation of Forge or Bukkit.

Also, looking at 1.18.2 RestrictedPortals, I don't see how they could even be causing the Forge cap to not apply. They don't touch caps at all so they have no way of nuking the cap from the entity as caps is a thing that Forge itself applies to all entities on their creation. RestrictedPortals can't stop that
https://github.com/MoreThanHidden/RestrictedPortals/blob/1.18.2/src/main/java/morethanhidden/restrictedportals/handlers/EventHandler.java

I went and did a test with 1.18.2 RestrictedPortals and Bumblezone on Forge alone and it works just fine. I am able to teleport to Bumblezone without issue
![image](https://github.com/TelepathicGrunt/Bumblezone/assets/40846040/63cfefaa-66b6-460f-94bb-518d47dc68f8)

Which leads us to what the likely real cause is. Magma. Because Magma is really the only one that would interfere with Forge on a fundamental level such as caps attaching as if they messed up the implementation, they could cause an entity not to have the caps they were suppose to have.

I'm not just knee-jerking on Magma. I'm speaking from experience that these hybrids always causes these kinds of issues that never are reproducible with just Forge alone. In fact, Mohist, another hybrid, had this literal exact same issue lmao (Well they say it was due to craftbukkit). See the issue report I made to them here where they had to fix how they implemented Forge caps so it seems incredibly likely that Magma is also making the same mistake. https://github.com/MohistMC/Mohist/issues/696
