### ISSUE TITLE
1.19.2 - Enlightend causes Rubidium/Embeddium to not render blocks in Bumblezone

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [TelepathicGrunt/Bumblezone#267]
You can read this for now I will just be removing mod.
https://gist.github.com/P3rf3ctXZer0/3fdff113fb29533f71e4b30da12f45ab

If you want to test against it use this work space.

https://www.curseforge.com/minecraft/modpacks/fiction-friction-pixelmon

**Comment by TelepathicGrunt** [comment]
I don't see how this is related to Bumblezone. Just looks like an issue with starlight

**Comment by TelepathicGrunt** [comment]
If the main issue is that block models are not rendering in bumblezone dimension, that starlight error is not at all part of that. That's entirely separate. Instead, I disabled rubidium-0.6.2b.jar and the mod block shows up just fine. Try Embeddium instead of Rubidium. Seems embeddium has issue as well within your pack. A third mod is at play causing both Embeddium and Rubidium to struggle to work in Bumblezone dimension. You are going to have to hunt down that third problematic mod
![image](https://github.com/TelepathicGrunt/Bumblezone/assets/40846040/cc5f248a-079d-4a04-b64e-cd3556c23a8f)

**Comment by TelepathicGrunt** [comment]
Also, get rid of memorysweep. It's placebo and is not going to help with your memory and probably will cause lags every time it runs.

**Comment by TelepathicGrunt** [comment]
It's Enlightend that is the issue. Embeddedt helped me adjust the Bumblezone baked models to be correct for Forge so my baked models should be fine. However, something about Enlightend breaks both Embeddium and Rubidium to the point they cannot render any model of any block in Bumblezone dimension. 
![image](https://github.com/TelepathicGrunt/Bumblezone/assets/40846040/3a6c8da8-20dd-482c-ac16-44bc678522e6)

You may want to reach out to Enlightend and show them this comment of mine that narrowed it down to an interaction with them.

**Comment by P3rf3ctXZer0** [comment]
Thank you so much I will remove Enlightend for the time being :D I would report it to the dev but they are using discord as report space and I have a pet peeve against force boosting discord numbers.

Added to list of problem child mods. I will remove memory sweep - if it is useless to force gc it can leave.

**Comment by TelepathicGrunt** [comment]
Reopening so other users can see this issue exists

**Comment by P3rf3ctXZer0** [comment]
Wouldn't it be an easier thing to add to a currently incompatible mods than link this issue even if closed?

**Comment by TelepathicGrunt** [comment]
Keeping it open makes it more visible here for people to see if they check GitHub: 
![image](https://github.com/TelepathicGrunt/Bumblezone/assets/40846040/d3be88ed-ed38-4342-9fd5-3e3d0ed381ba)

And I cannot contribute to Enlightend as they are a closed source Mcreator mod. I rather not mark the mod as incompatible on Curseforge because the incompat requires a third mod (rubidium/Embeddium) to be on as well and the sites don't handle three way incompat marking very well.

**Comment by P3rf3ctXZer0** [comment]
Added a special thanks for you in my modpack ``TelepathicGrunt - For helping me figure out a strange fog issue caused by trinity mod clash aka 3+mods.``

**Comment by TelepathicGrunt** [comment]
new workaround, disable thickFog in Bumblezone's dimension config file

**Comment by TelepathicGrunt** [comment]
v6.7.35 Bumblezone should in theory fix this by switching to forge event and not reverse start and end fog distance by mistake.

**Comment by embeddedt** [comment]
The Embeddium part of this incompatibility has been resolved in Embeddium 0.1.11, by tweaking the fog behavior to act identically to vanilla when the start and end distance is swapped by mods.
