### ISSUE TITLE
1.20.1 Text bug

### ISSUE THREAD

**Issue by Nekobrenna** [TelepathicGrunt/Bumblezone#283]
Not sure what is going on with the bumblezone, but the title text is all messed up after installing it into my mod pack. If you need a log, please reply back on this bug and I will send you a log.
![The Bumblezone bug](https://github.com/TelepathicGrunt/Bumblezone/assets/133595839/651734b5-316b-46da-a54a-2ef3896a141b)

**Comment by TelepathicGrunt** [comment]
What modloader and what modpack and what about latest.log? This issue has not happened to me so I am very suspicious that this is even my mod’s fault. Likely a resource issue from another mod that could be having a race condition and so, doesn’t always show up with the issue

**Comment by Nekobrenna** [comment]
[bumblezone_installed_glitch.log](https://github.com/TelepathicGrunt/Bumblezone/files/12910877/bumblezone_installed_glitch.log)

**Comment by Nekobrenna** [comment]
If I knew more about coding, I'd try and fix it myself. I really appreciate you looking into this.

**Comment by TelepathicGrunt** [comment]
Your log shows several issues.

![image](https://github.com/TelepathicGrunt/Bumblezone/assets/40846040/d5eeafea-d630-4c75-a274-a62d195dae84)
The resourcepack failed to load (which holds the text and all that) because of elytratrims mod. Update that mod if possible. If already on latest, report the issue to them. It looks like your title screen issue is because of them.

Also,
![image](https://github.com/TelepathicGrunt/Bumblezone/assets/40846040/6db5c6a7-e2d5-4e55-ad8b-56137676850d)

There are some errors in your log shows Supplementaries is unable to generate the sign texture for several mods. Please make sure you updated Supplementaries and Moonlight lib to latest. This is not likely to cause issue with your game's text but might be good to report to Supplementaries's dev to see if they want to look into it and ask the other modders to register their sign types correctly.

**Comment by Nekobrenna** [comment]
Cool, thanks!

**Comment by TelepathicGrunt** [comment]
Gonna close this for now since it doesn’t appear to be Bumblezone related
