### ISSUE TITLE
essence of raging challenge

### ISSUE THREAD

**Issue by kaboom24** [TelepathicGrunt/Bumblezone#298]
the bar at the top says lose in howevert long not win

**Comment by TelepathicGrunt** [comment]
The bar is correct. The progress bar is how many mobs to kill. If you kill all mobs, the bar reaches 0 and you win. The “lose in xx:xx” is saying how much time you have left before you lose.

basically the text say how much time is left. The bar is how many mobs to kill and your progress toward beating it.

If you try to wait out the timer, you should lose

**Comment by kaboom24** [comment]
then what about the essence of calming shouldnt it be try to survive not try to kill its literally essence of calming

**Comment by TelepathicGrunt** [comment]
Essence of calming is also killing all mobs as surviving mobs is easy (just go around room in a circle) and I could not figure out a minigame that’s more calm and challenging. I also wanted it underwater to match the blue of calming. So that’s what I settled on and I do not want to change it as it is far too much work. 

Also note, the arena minigame doesn’t always reflect the item’s name and behavior. Continuity is kill crystals while the item is basically a better totem of undying. Radiance event is about avoiding vexes and jumping through rings but the item is about getting boosts in sunlight. Life event is about wacking dirt pellets back at a rootmin but the item is about healing. 

The mini games mechanics are not tied to how the items work

**Comment by kaboom24** [comment]
alright

**Comment by kaboom24** [comment]
one more thing whenever I get close to beating the calm minigame it pauses and stops working and I have to restart the game but it never crashes just freezes forever so I cant send you a crash log also great mod

**Comment by kaboom24** [comment]
finally when I complete some of the trials the room does not return to its original state

**Comment by TelepathicGrunt** [comment]
> one more thing whenever I get close to beating the calm minigame it pauses and stops working and I have to restart the game but it never crashes just freezes forever so I cant send you a crash log also great mod

> finally when I complete some of the trials the room does not return to its original state

These issues I will need as a new issue report and a link to the modpack you're playing with. If it is a custom modpack, you can export it and share it with me (can use google drive or dropbox with the link sharing set to public) I will also need to know what modloader you're playing on and what you mean by original state for rooms. Also, single player or server?

**Comment by kaboom24** [comment]
single player and ok also I figured out the problem with the room not returning its just the pause in the calming one

**Comment by kaboom24** [comment]
also curseforge is the mod loader

**Comment by TelepathicGrunt** [comment]
Curseforge is the mod launcher and mod website. Mod loaders are the actual systems that loads the mods into Minecraft. Examples are Forge, Fabric, Quilt, or Neoforge

**Comment by kaboom24** [comment]
oh forge
