### ISSUE TITLE
Tons of Lag in Bumble Dimension 

### ISSUE THREAD

**Issue by Withergaming101** [TelepathicGrunt/Bumblezone#31]
Title says it all. Ill upload my log.
[latest.log](https://github.com/TelepathicGrunt/Bumblezone/files/5504082/latest.log)

**Comment by TelepathicGrunt** [comment]
I'm not seeing anything too out of the ordinary. Can you make a copy of the world, enter it, and do `/kill @e[type=bee] `? It might be that there's too many bees that the server is dying as a result because mojang didn't optimize the bee AI at all.

**Comment by TelepathicGrunt** [comment]
Anyone else reading this, it was bees lol. Lots of bees. oh god the bees!

**Comment by Spongman** [comment]
I'm seeing the same thing. just entered the dimension, it takes over 5 seconds for a block to break. no issues in the overworld (or the nether).

**Comment by TelepathicGrunt** [comment]
@Spongman there is but the brood blocks tends to ignore it. After I finish porting ultra amplified mod, I'll come back to this, add config option to turn off brood blocks and see if i can make them only spawn bees till the area hits maybe 3x or 4x the mob cap instead of unlimited. The issue is mojang's bee ai is dumb as heck and will cause bee to fly upward to the ceiling and get stuck. The broods were suppose to spawn bees so players can see bees around instead of no bees because they are all stuck on the ceiling. I want to see if I can fix the bee ai too.

**Comment by TelepathicGrunt** [comment]
Reopening until I get around to addressing the issue

**Comment by TelepathicGrunt** [comment]
v2.2.9 is now out and should help this issue!
https://www.curseforge.com/minecraft/mc-mods/the-bumblezone-forge/files/3166041

What I had done is made Vanilla bees use my own custom AI when wandering in The Bumblezone dimension. This new AI is much lighter in performance and makes bees fly around in the air more evenly instead of clustering on the ceiling forever. Brood Blocks now will not automatically spawn bees over time if there's too many bees around (capped at 40 bees and can be changed by config). 

Hopefully this helps!
