### ISSUE TITLE
  Kicked from paper hub. lost connection: Invalid payload REGISTER!

### ISSUE THREAD

**Issue by Darmoed228** [TelepathicGrunt/Bumblezone#315]
Hello. With your mod can not go to the hub to further from there to go to fabric server. I created a modpack with your mod and wanted to add the fabric server to the velocity network, but your mod does not let me into it. Is there any way to fix this? the_bumblezone-7.1.9+1.20.1-fabric

[https://pastebin.com/xyM0sFfB](url)

**Comment by TelepathicGrunt** [comment]
I don't know what a "hub" is nor "velocity network" is that much. All I support is my mod being put on a proper modded server.

If you are trying to connect to a vanilla server with my mod on client, that will never work because my mod is a content heavy mod that registers a ton of stuff and modifies quite a bit of code. It will always blow up trying to connect to vanilla/plugin servers. I only support my mod being on both client and the server as then the networking and registries and code behaviors would be correctly in sync. 

Also I have no idea why bukket would limit channel name length. Seems like a bukket problem for themselves

**Comment by Darmoed228** [comment]
I thought you were interested in having servers with your mod on servers that are networked together. Then I apologize for the inconvenience. It's a shame that a server with a large modpack will not have your mod.

**Comment by TelepathicGrunt** [comment]
@Darmoed228 There's nothing I can do. I do not do explicit support plugins because they are not mods and are far too much work for me to deal with (hybrid servers are always broken in some way or dont implement the modloader's features properly) and I have no way of testing with plugin stuff as I do not want to significantly increase my workload with spinning up plugin servers and testing with them. 

For the channel name limit, that's nothing to do with my mod. That's a limit imposed by paper that they should remove. Please provide full details of your setup to Paper at this issue report to them. Especially if this channel name limit is the only thing keeping your Velocity server thing from working: https://github.com/PaperMC/Paper/issues/10003
