### ISSUE TITLE
[Crash with Identity and Gravity Changer] Crashing singleplayer when opening the Identity menu

### ISSUE THREAD

**Issue by Neo-Qwerty** [TelepathicGrunt/Bumblezone#317]
- Fabric Loader 0.15.1
- Minecraft 1.20.1
- Bumblezone 7.1.10 for Fabric 1.20.1
- Identity 2.7.1
- Gravity Changer (qouteall fork) 1.1.2 (on modrinth)

I'm unsure if the crash happens with just Gravity Changer (qouteall) or with just Identity, but with both and Bumblezone I get this crash log after trying to open the Identity menu:
[crash-2023-12-12_19.08.03-client.txt](https://github.com/TelepathicGrunt/Bumblezone/files/13654504/crash-2023-12-12_19.08.03-client.txt)

**Comment by TelepathicGrunt** [comment]
Lets see. Identity iterates over the entire entity registry and tries to construct every entity.
https://github.com/Draylar/identity/blob/2fdf47a7c8c727f05460378247ff118f868f0713/common/src/main/java/draylar/identity/api/variant/IdentityType.java#L91C35-L91C35

Sentry Watcher gets created and as part of setup, tries to orient in a cardinal direction like north, south, east, or west. Sentry Watch starts by calling getDirection() which is a vanilla method for entity and should be safe to call.
https://github.com/TelepathicGrunt/Bumblezone/blob/d6275f68b46c325df131c047a5462a2ab547f010/common/src/main/java/com/telepathicgrunt/the_bumblezone/entities/nonliving/SentryWatcherEntity.java#L125

GravityChangerAPI by quoteall tries to get a gravity component off of the Sentry Watcher. It seems GravityAPI is crashing due to null within their gravity data code but only for Sentry Watch and I have no idea why
https://github.com/qouteall/GravityChanger/blob/819638d934911f851d04cdef13504857db9df750/src/main/java/gravity_changer/api/GravityChangerAPI.java#L101

This looks more like an issue for GravityAPI devs to take a look at

**Comment by TelepathicGrunt** [comment]
Gravity Changer mod has fixed this in 1.20.2 and newer. Not sure they will backport. Closing this now
