### ISSUE TITLE
Issue with shield overhaul. Cannot shield bash

### ISSUE THREAD

**Issue by Fuegofandango** [TelepathicGrunt/Bumblezone#318]
[crash-2023-12-12_20.02.46-client.txt](https://github.com/TelepathicGrunt/Bumblezone/files/13655435/crash-2023-12-12_20.02.46-client.txt)

I'm using 6.8.2. Every time I try to shield bash using Shield_Overhaul-FABRIC-MC1.19.2-1.0.3, the game crashes. See the attached log. This happens with any shield. Disabling Bumblezone fixes the issue.

**Comment by TelepathicGrunt** [comment]
Please give me a link to where I can download your modpack (you can export and put it into google drive or dropbox and set link to public for me to download)

You have a much larger issue here. The crash isn't bumblezone. There's a projectile being handled to bumblezone and when bumblezone calls saveWithoutId on the projectile, the projectile crashes because someone gave it an incorrect soundevent that does not exist. All projectiles and entities should be safe to call saveWithoutId. The fact this is crashing means someone done goofed with their entity and I can't shield against that in my mod because this is internal data within the projectile and the saving behavior is handled by the projectile itself. 

If you give me modpack, I can have a better shot and tracking down who it is

**Comment by TelepathicGrunt** [comment]
Actually, here, extract the jar from this zip file. Reproduce the crash with this bumblezone jar. And then give me the latest.log file from the logs folder above mods folder. I added some logging that should say exactly what projectile from who was given to bumblezone right before the crash
[the_bumblezone_fabric-6.8.2-test+1.19.2.jar.zip](https://github.com/TelepathicGrunt/Bumblezone/files/13655529/the_bumblezone_fabric-6.8.2-test%2B1.19.2.jar.zip)

**Comment by Fuegofandango** [comment]
Thank you for you looking into this so fast! My modpack is entirely custom made. I use prism launcher. I just used the custom JAR and got these:
[crash-2023-12-12_20.49.53-server.txt](https://github.com/TelepathicGrunt/Bumblezone/files/13655677/crash-2023-12-12_20.49.53-server.txt)
[crash-2023-12-12_20.49.58-client.txt](https://github.com/TelepathicGrunt/Bumblezone/files/13655678/crash-2023-12-12_20.49.58-client.txt)

**Comment by TelepathicGrunt** [comment]
those are crashlogs. They do not help at all because they only show the crash. I need the latest.log file from the logs folder after the crash happens. The latest.log have *all* the log entries including my logging I added

**Comment by Fuegofandango** [comment]
Ah okay, gotcha. Here it is: 
[latest.log](https://github.com/TelepathicGrunt/Bumblezone/files/13662857/latest.log)

**Comment by TelepathicGrunt** [comment]
> [20:49:53] [Render thread/ERROR]: PROJECTILE FOUND: ShieldBashEntity['entity.shield_overhaul.shield_bash_entity'/551, l='ClientLevel', x=24.12, y=-58.48, z=-9.76]
> [20:49:53] [Render thread/ERROR]: PROJECTILE RL: shield_overhaul:shield_bash_entity

What in the world? Shield Overhaul has their own entity projectile being the shield bashing? Huh

**Comment by TelepathicGrunt** [comment]
This is the issue. That's the unregistered sound event that will crash even vanilla itself. I'll poke at the dev
https://github.com/nvb-uy/Shield_Overhaul/blob/3aaa1c59875e6ec5c4af37d36891edd8284c7160/src/main/java/elocindev/shield_overhaul/entity/ShieldBashEntity.java#L61

**Comment by TelepathicGrunt** [comment]
![image](https://github.com/TelepathicGrunt/Bumblezone/assets/40846040/b1b92fa5-42a8-4fac-b82c-ba4746e7cedc)


If no reply by tomorrow night, I'll make issue report in their repo and link this issue to it

**Comment by Fuegofandango** [comment]
![image](https://github.com/TelepathicGrunt/Bumblezone/assets/55003217/75d73a05-5b1a-42c7-8b7a-71619ba191ad)
I'm in the server too. I'll disable the shield overhaul mod in the meantime. Thank you so much!
