### ISSUE TITLE
Soup gives THREE HUNDRED SIXTY saturation?

### ISSUE THREAD

**Issue by Aceplante** [TelepathicGrunt/Bumblezone#321]
this is absolutely ludicrous and there is no way it should give that much

1.20.1

**Comment by TelepathicGrunt** [comment]
You’re gonna need to be far more specific on where you see that. Bee soup has 24 saturation as specified here which is about double of cooked steak’s 12.8 saturation due to needing extra ingredients to make the bee soup and also balanced by bee soup has chance to give negative effects to eater.

https://github.com/TelepathicGrunt/Bumblezone/blob/117c9da266e369416505c5d71a02a5686b2f05fe/common/src/main/java/com/telepathicgrunt/the_bumblezone/modinit/BzItems.java#L168

**Comment by Aceplante** [comment]
![uhh](https://github.com/TelepathicGrunt/Bumblezone/assets/101857505/275a305f-56a4-4468-b0f5-92327d2652db)

**Comment by Aceplante** [comment]
this is appleskin that shows me

**Comment by TelepathicGrunt** [comment]
This seems like an appleskin bug but I'll verify with the dev. The picture is showing Bee Soup (and Bee Bread) with hunger effect food icons despite my items not giving hunger.

**Comment by TelepathicGrunt** [comment]
Nah it's me. MC sets up the values weirdly 
![image](https://github.com/TelepathicGrunt/Bumblezone/assets/40846040/26f1e382-f61f-4baa-8b63-9a705fef04c4)

**Comment by Aceplante** [comment]
Yea, dont worry. Ive seen quite a few other mods with crazy saturation values, likely for this very reason

**Comment by TelepathicGrunt** [comment]
Should be fixed in newest jars now. Max saturation should be around 20 saturation or slightly less. Bee Bread is also slightly nerfed
