### ISSUE TITLE
trying to trade with more than one snowball throws it instead of trading

### ISSUE THREAD

**Issue by Lazerpie101** [TelepathicGrunt/Bumblezone#334]
When holding more than one snowball in my hand, the game throws the snowball instead of trading it.

**Comment by TelepathicGrunt** [comment]
Drop the snowball onto the ground and the queen will trade with it. Snowball throwing is controlled in the item itself before the entity interact logic is ran. So snowball throwing instead of trading on right click is the intended vanilla behavior as item behavior takes priority over entity interact. Hence the solution is just drop the item instead. You will still get credited for that trade when dropping items to trade.

**Comment by TelepathicGrunt** [comment]
Ok thought about it some more. What I can do is hardcode check for if snowball is thrown at bee queen and if she has a trade for snowball active, she will take no damage from snowball and give clay. Basically catching the snowball. This will be specifically only for snowball. Other projectiles will not be special cased. New version of bumblezone is now released with this small change
