### ISSUE TITLE
Waterlogged honey crystals break translucent sorting

### ISSUE THREAD

**Issue by Lolothepro** [TelepathicGrunt/Bumblezone#381]
https://github.com/TelepathicGrunt/Bumblezone/assets/68275908/5a00fa55-3c4e-4a1b-ad5c-82f86fc24e54

With Minecraft Vanilla + Bumblezone, sorting seems slightly broken

**Comment by TelepathicGrunt** [comment]
If vanilla issue, there isn’t anything I can do. The quads are correct as far as I know and I am not gonna modify the vanilla translucent sorting system

**Comment by Lolothepro** [comment]
Can you check if it's fixable?

**Comment by TelepathicGrunt** [comment]
Fix it how?

It’s a vanilla issue with vanilla’s own translucent sorting system which I won’t touch due to it having bugs and fragile and I don’t want to break anyone else nor decrease its performance with extra checks. 

And the crystal has to remain translucent for its looks. I don’t want to make it opaque just to address this waterlogged edge case.

Not everything is worth fixing

**Comment by douira** [comment]
I've fixed this in sodium with the new translucency sorting system. It required some extra tuning to properly detect and use the existing mitigations for such intersecting geometry, but it works now.

With vanilla's quad-center distance-based translucency sorting this is broken since the waterlogged model intersects with the water and there's small quads in the model whose centers are closer to the camera than the big water quad center is at certain viewing angles.

![Screenshot 2024-05-09 at 05 34 53](https://github.com/TelepathicGrunt/Bumblezone/assets/17120022/57bfc515-e6bb-4e63-98cd-760fff386cf0)

**Comment by TelepathicGrunt** [comment]
Alright but this is about my mod Bumblezone and what I can do which is nothing. It is out of scope of my mod to completely replace the translucency sorting system. Another mod can do so to fix the issue but not me.
