### ISSUE TITLE
Minecraft crashes whenever any entity is submerged on any of it's liquids

### ISSUE THREAD

**Issue by macuguita** [TelepathicGrunt/Bumblezone#389]
Most of the times this only crashes the client, but on some rare occasions it crashes the server, this happens with royal jelly and honey, so the "viscous" fluids, this did not happen with sugar water.

https://mclo.gs/zoNyveJ

**Comment by TelepathicGrunt** [comment]
`handler$ehn000$star$checkIfCustomFluidIsBreathable`

This is a repeat of https://github.com/TelepathicGrunt/Bumblezone/issues/385

Basically, `star` mod had a broke mixin. They have since updated their mod. Stars is used by the Fabric tinkers mod (Hephaestus).

So update stars or Hephaestus and issue should go away
