### ISSUE TITLE
Blue Sempiternal Sanctum's Guardian's beams do constant damage, stunlocking the player in place, making the Sanctum nearly impossible to beat

### ISSUE THREAD

**Issue by Inonedn** [TelepathicGrunt/Bumblezone#412]
NeoForge version: 21.0.76
Minecraft Version: 1.21
In exchange for the rapid damage they can do, they should instead deal much higher damage per cycle

**Comment by Inonedn** [comment]
https://youtu.be/lJheZ4Ny7cM

**Comment by TelepathicGrunt** [comment]
You're trying to swim towards them while they are attacking you. That's their knockback direction. Face sideways and swim. I beaten this event many times myself with the reduced beam attack timer and have been hit many times by the guardians and not been stuck when I swim away from the beam attack. if you try swim towards it even slightly, it'll kill your speed. You have to face backwards and use the knockback to push you to cover. 

See here where I managed to swim out of the beam attack multiple times and at end, swimming towards it is what gets me stuck due to killing my speed
https://github.com/TelepathicGrunt/Bumblezone/assets/40846040/c3efa910-928d-4695-a7b1-6461c7eda2d9

Closing this as this is more of a player issue. Adding back the cooldown between beam hits would make the arena far too easy and I feel I am already making it a bit too easy due to respiration 3 helmet and loyalty impaling tridents

Edit: Video was me without depth strider. Putting on max depth strider makes it very easy to swim to safety while being hit with beam too. Basically, be prepared for this arena it isnt too bad a challenge
