### ISSUE TITLE
Beehemoth speed config doesn't seem to work

### ISSUE THREAD

**Issue by shmove** [TelepathicGrunt/Bumblezone#440]
Does the "beehemothSpeed" config also apply to the Queen Beehemoth? Despite changing this setting serverside, it remains just as fast. Not sure if this is the case for the regular Beehemoth as well.

**Comment by TelepathicGrunt** [comment]
Need minecraft version and modloader please. Also change the speed on client too. Entity speed is handled on both client and server so both sides need to match for the speed config

**Comment by shmove** [comment]
Versions: Minecraft v1.21, Fabric loader v0.16.3, Fabric API v0.102.0+1.21.

Is it really something that needs to be changed on the client too? How would I enforce this on a server?

**Comment by TelepathicGrunt** [comment]
Usually pack makers make the change to config and then distribute the modified modpack to clients. 

Entity speeds is handled on both sides because if it wasn’t, you would stutter as you would only move when you receive packets from server. So client has to do motion calculations on its side and then check if it is matching server expected position every so often.

For me to make the config sync from server to client, is annoying. Midnightlib does not have config syncing. Neither does forge/neoforge. So I would need to make a packet that is sent from client when client joins to server, server gets config value, goes back to client, and sets the value on client. And server needs to also broadcast packet when its value is changed. My codebase is not setup nicely to allow this. It would take me time to do something

**Comment by TelepathicGrunt** [comment]
should be fixed in v7.5.0 in 1.20.1 and v7.7.0 in 1.21.1
