### ISSUE TITLE
Possible replacement for Flight of the Bumblebee midi disc

### ISSUE THREAD

**Issue by FeeshUnofficial** [TelepathicGrunt/Bumblezone#442]
There is an audio file of Flight of the Bumblebee available on archive.com that falls under public domain. 
https://archive.org/details/FlightOfTheBumblebee

This will probably sound a lot better than the midi version you're using now.

**Comment by TelepathicGrunt** [comment]
Last time I tried to get a royalty free song, I contacted the musician to make sure. Turned out the public domain site stole his music and put it on their free-to -se site without his knowledge. So I don’t exactly trust any songs that are “free-to-use” unless explicit permission from the musician can be obtained. So instead, I got the digital sheet music of flight of the bumblebee (just the notes) and fed it into a medi software to get the music for it (I think it was famitracker?) so I can get less worry about accidentally stealing someone’s work. 

So forgive me for closing this but again, I won’t consider taking musics online unless you can get the creator of the song to give explicit permission or get another musician to contact me to make the song
