### ISSUE TITLE
Fluids (Fluid Honey/Royal Jelly) does not show texture, OptiFine incompatibility

### ISSUE THREAD

**Issue by Khamircia** [TelepathicGrunt/Bumblezone#466]
With OptiFine installed (with or without using shaders) fluids are invisible (Honey/Jelly/Lava/Sugar Water):
![2024-12-16_23 19 26](https://github.com/user-attachments/assets/f56a040f-bb6f-4aa3-95bf-ad1e6de36e99)
For comparison, totally without OptiFine (Honey/Jelly/Lava/Sugar Water):
![2024-12-16_23 08 45](https://github.com/user-attachments/assets/1cc15811-5a41-49f5-9378-8cbdf42679c9)
Fluids from other mods work well WITH OptiFine (green one is acid from Alex's Caves) (Honey/Jelly/Lava/Sugar Water/Acid):
![2024-12-16_23 20 37](https://github.com/user-attachments/assets/b96c57cb-f85a-404a-b7e4-46687ebecbbc)

Minecraft 1.20.1 
Forge 47.2.0
OptiFine_1.20.1_HD_U_I6
the_bumblezone-7.5.5+1.20.1-forge
alexscaves-1.1.5 (for comparison and potential solution for non-invisible fluids)

PS. U R Awesome and have a nice day full of fluffy kittens <3

**Comment by TelepathicGrunt** [comment]
I do not support optifine and you shouldn't be using it either. It is an ancient jarmod that replaces large swathes of code unsafely while being closed source and impossible to support (or well, far too painful to support since they refuse to remake optifine as a proper forge mod). For 1.20.1 Forge, use Embeddium and Oculus to get shader. Or just Embeddium for performance.
