### ISSUE TITLE
smacking a bee causes crash/kick

### ISSUE THREAD

**Issue by STOKE-STER** [TelepathicGrunt/Bumblezone#5]
When hitting a bee in survival on singleplayer, my game instantly crashes. The bee is in the overworld. Hitting one in creative does nothing so I'm assuming something to do with the bee being enraged is making me crash. I also tested this on a server and the server didn't crash or my client but it did kick me. 

[crash-2020-05-17_02.46.40-server.txt](https://github.com/TelepathicGrunt/Bumblezone/files/4638776/crash-2020-05-17_02.46.40-server.txt)

**Comment by TelepathicGrunt** [comment]
looks like this is an issue with Potion Master. I wish they were open sourced so I can see what they are doing but from the crashlog, it seems they are using a Forge event that fires when potion effects are removed. And that is causing a crash somehow. They might had forgotten a null check somewhere. I'll try and open an issue report with them to see if they can fix it on their end.

Next update will also fix the bug where bees cannot be angered in the overworld so maybe next update will help reduce this crash from happening but I suspect it'll still be possible to cause the crash since the real underlying issue will still be present.

**Comment by TelepathicGrunt** [comment]
Made a crash report to Potion Master here. Now we have to wait until they respond to see how to fix this issue for good.
https://www.curseforge.com/minecraft/mc-mods/potionsmaster/issues/10

But yeah, thank you for reporting this!

**Comment by TelepathicGrunt** [comment]
Oh I just saw another issue report for their mod. https://www.curseforge.com/minecraft/mc-mods/potionsmaster/issues/9

That person's crashlog is pointing to Potion Master's potion remove event as well. Yeah it definitely an issue on their end if it is crashing servers on startup too lol. Hopefully they can fix this crash soon!

**Comment by STOKE-STER** [comment]
Thanks for the speedy response :) two very great mods that I'd love to see working as intended again lol

**Comment by TelepathicGrunt** [comment]
Almost forgot about this! I went and tested this issue with potionsmaster-0.1.8-1.15.2-31.2.0.jar to see if it still happens. And well, the crash seems to be fixed! I'll close this issue report now. :)
