### ISSUE TITLE
[1.16.5-Forge] Config generates .bak copy every time the game starts up.

### ISSUE THREAD

**Issue by Gbergz** [TelepathicGrunt/Bumblezone#57]
### **Title ^**

In newer versions of Forge the config file for the Bumblezone generates a new config with the file extension ``.bak`` each time the game starts.

> Example:
![image](https://user-images.githubusercontent.com/26634554/110473931-60801080-80df-11eb-913b-3a392a83ae24.png)

I know this happens/happened to other mods but got fixed after awhile, think it has to do with some recent forge changes.

Minecraft: ``1.16.5``
Forge: ``36.0.46``
Bumblezone version: ``2.2.14``

**-** Gbergz

**Comment by TelepathicGrunt** [comment]
This is caused by a bug in forge that really doesn’t like configs having empty string defaults or having \r in the comments. https://github.com/MinecraftForge/MinecraftForge/issues/7669

I can edit my config file to work around the issue but keep watch on Forge for the true fix that will stop all the other mod’s bak files being made

**Comment by TelepathicGrunt** [comment]
Forge beat me to it lol. They released an update to try and fix the generation of .bak files. Can you try Forge 1.16.5-36.0.53 and see if the problem still persists? If it is resolved, I'll close this report as it's no longer a problem

Forge changelog:
https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.16.5-36.0.53/forge-1.16.5-36.0.53-changelog.txt
Build: 1.16.5-36.0.53 - Fri Mar 12 00:11:22 GMT 2021
	curle:
		Automatically fix some issues with configurations deemed invalid for simple reasons (#7671)

**Comment by Gbergz** [comment]
Confirmed fixed in ``Forge-36.0.53`` 👍
