### ISSUE TITLE
Dimensional teleportation 

### ISSUE THREAD

**Issue by disastercube** [TelepathicGrunt/Bumblezone#6]
It is a nice addition that to escape the dimension you have to dig either up or down but when you get teleported out and you find yourself in the middle of nowhere with a bee nest underneath you it looks really strange. It would look much better if you were to come back from the same nest you entered or at least a feature that would allow you to come back from your own bee nest.

**Comment by disastercube** [comment]
This also could be used to duplicate hives which would be a real game braking mechanic and it ruins the whole experience just knowing that'll happen

**Comment by TelepathicGrunt** [comment]
The issue with exiting to the same hive block is that the hive could be removed and such and it would make using The Bumblezone for fast travel not possible anymore. However, next update will have a new config to let players customized the teleportation better to what they perfer!

teleportationMode config will have 3 modes. Mode 1 will be the original teleportation that occurs right now where coordinates are converted and the player will spawn at the new location near a beenest or generates a beenest if non is found. Mode 2 will spawn players always at their original spot that they were at in the non-Bumblezone dimension even if the original Beenest was destroyed. And Mode 3 will be a mix where it will convert coordinates, look for a nearby beenest to spawn players at, and if non is found, spawn players at their original location instead of the converted coordinates.

Anotehr config will be added called generateBeenest config that will let players turn on or off the generation of extra Beenests for teleportation mode 1.

Stay tuned and thank you for your feedback!

**Comment by TelepathicGrunt** [comment]
v1.3.4 is now out with new config options to change the teleportation mode and whether to spawn beenests or not! https://www.curseforge.com/minecraft/mc-mods/the-bumblezone-forge/files

I'll close this issue report now

**Comment by disastercube** [comment]
Nice, thank you so much for telling me. Appreciated
