### ISSUE TITLE
Strange Incompatibility with Advanced Mining Dimension and/or BetterNether Reforged

### ISSUE THREAD

**Issue by seanimusprime** [TelepathicGrunt/Bumblezone#76]
Since adding BetterNether Reforged to my server, our mining dimension's biomes keep getting overwritten with biome properties from BetterNether and The Bumblezone. As far as I'm aware, this issue didn't exist before adding BetterNether. The biomes themselves are not generating, just the properties (fog color, water color, ambient music, mob spawning, etc). The mining dimension is supposed to be peaceful, no mobs spawning at all, but now there are bees and nether mobs spawning.

I have already reported the issue to the mining dimension and better nether authors
https://github.com/Someone-Else-Was-Taken/BetterNether-Reforged/issues/22
https://github.com/henkelmax/advanced-mining-dimension/issues/59

**Comment by TelepathicGrunt** [comment]
Sounds like you had the biome shuffling bug where the addition of new biomes caused the internal ids to shift. In Mc all the way until 1.18, biomes are stored in the chunk by their numeric IDs instead of their resourcelocation. So if new biomes are added by datapack or mods, there’s a chance the old biomes are shifted to a different Id and the world now reads the generated biomes as a different biome instead.

Forge tried to fix this so if their fix for these biome shifts isn’t working, then there’s not much you or I can do. You could try using a mod called Chocolate Fix but again, their mod page says to update forge instead  https://www.curseforge.com/minecraft/mc-mods/chocolate-fix

There’s another mod out there where players can manually assign the int id to biomes too but I forgot the name of it.

I’ll also double check mining dimension’s biome source just in case it isn’t setup right as well in case it breaks with the addition of new biomes.

**Comment by seanimusprime** [comment]
> Sounds like you had the biome shuffling bug where the addition of new biomes caused the internal ids to shift. In Mc all the way until 1.18, biomes are stored in the chunk by their numeric IDs instead of their resourcelocation. So if new biomes are added by datapack or mods, there’s a chance the old biomes are shifted to a different Id and the world now reads the generated biomes as a different biome instead.
> 
> Forge tried to fix this so if their fix for these biome shifts isn’t working, then there’s not much you or I can do. You could try using a mod called Chocolate Fix but again, their mod page says to update forge instead https://www.curseforge.com/minecraft/mc-mods/chocolate-fix
> 
> There’s another mod out there where players can manually assign the int id to biomes too but I forgot the name of it.
> 
> I’ll also double check mining dimension’s biome source just in case it isn’t setup right as well in case it breaks with the addition of new biomes.

I have chocolate fix and Biome ID Fixer and the biomes are still being shuffled. Forge is also updated to the most recent 1.16.5 version as well.

**Comment by TelepathicGrunt** [comment]
yeah i'll close this as it is that biome shuffling bug and you already got a workaround in the other issue report. No clue why forge broke. I'm hoping it was a one time thing.
