### ISSUE TITLE
1.18.1 Crash w/ Optifine

### ISSUE THREAD

**Issue by GamerGaven** [TelepathicGrunt/Bumblezone#92]
Will immediately crash upon loading the game up.
[crash-2021-12-19_13.21.36-client.txt](https://github.com/TelepathicGrunt/Bumblezone/files/7741657/crash-2021-12-19_13.21.36-client.txt)
.

**Comment by TelepathicGrunt** [comment]
Just tested and wow. Optifine or well, optishit is so bad that they now mess with fluid rendering to the point it blows up my mixins lmao. I am not supporting optifine as it is a closed source, horrible mess of incompat hell. I still have bad memories of optifine breaking worldgen mods and also making mobs from structures be invisible which ruined a lot of people's hardcore worlds.

Nothing I can do. optifine should remake themselves into a proper mod instead of replacing entire classes in minecraft and wrecking modders. You can tell I have some serious beef with it lmao

**Comment by TelepathicGrunt** [comment]
Even when i tried switching to a more dangerous and fragile mixin, it turns out optifine breaks the coloring of my honey fluid so yeah, I am 100% not supporting optifine for how broken it is lmao 
![image](https://user-images.githubusercontent.com/40846040/146692290-21ce5294-1185-4a7e-9534-c89fdb8d3ec1.png)

**Comment by GamerGaven** [comment]
Totally understandable, other performance mods are available, just unfortunate optifine doesn't play nice with most mods.

**Comment by TelepathicGrunt** [comment]
thank you for reporting this tho. I pinned this report so other people who also crash can see this post and know why. Hopefully it'll keep people from spending too much time debugging their crash. Now I need to figure out how to make my curseforge page mark optifine as incompat hmmm

**Comment by zachsai** [comment]
Why is it incompatible with your fluids but not the Create mod's fluids...?

**Comment by TelepathicGrunt** [comment]
Don’t ask me lol. It’s closed source and wrecks everything. My mixin that’s as crashing is for making my honey fluid flow downward slowly with a bottom layer property. As for the color change, that’s probably an even worse nightmare to figure out

**Comment by zachsai** [comment]
![image](https://user-images.githubusercontent.com/63996164/146694154-6561b75f-4da5-4f4f-a1f2-27ac6de47d03.png)
Create has flowing honey and chocolate and works with optifine.
I am not writing this to be annoying, simply saying that reaching out to create for their input on how they went about it might help. 
I say this because I really want this mod to work with optifine :)

**Comment by TelepathicGrunt** [comment]
Their fluids are opaque while mine are translucent. Plus, their fluids are tagged as minecraft:water which impact some rendering stuff while my honey fluid is not tagged as water as it really isn't water. Furthermore, Create actually has a rendering issue where they break the screen overlaying in bumblezone's fluids. Issue report here for that: https://github.com/TelepathicGrunt/Bumblezone/issues/77

Their fluids and mine are very wildly different and if they are doing any extra stuff to support optifine, I will not be doing that. It's 2021, jarmods should dead by now and they all are except for optifine lol. Optifine should be remade into a proper forge mod so that the conflicts are no longer an issue or much easier to deal with.

As for performance mods on 1.18.1 you could try and use instead, 
https://www.curseforge.com/minecraft/mc-mods/sodium-reforged
https://www.curseforge.com/minecraft/mc-mods/lazy-dfu-forge
https://www.curseforge.com/minecraft/mc-mods/recipe-cache
https://www.curseforge.com/minecraft/mc-mods/ferritecore
https://www.curseforge.com/minecraft/mc-mods/entityculling
https://www.curseforge.com/minecraft/mc-mods/ai-improvements
https://www.curseforge.com/minecraft/mc-mods/get-it-together-drops

I was grabbing some of the performance mods from this list and checking if they have a 1.18 version: https://gist.github.com/alkyaly/02830c560d15256855bc529e1e232e88

**Comment by zachsai** [comment]
Yeah, tried them all together and it just doesnt compare to optfine. 
Immersive engineering just ported and they have fluids that are translucent and flow like water. Maybe they can help
![image](https://user-images.githubusercontent.com/63996164/146817666-e2e5edb5-61ab-4577-85dc-49b8e503cfa5.png)

**Comment by GamerGaven** [comment]
As much as I too would like compat, for the creators sake, the cons of having to upkeep with optifine heavily outweighs the pros. Optifine is known for cutting into systems that modders typically use which can cause rendering issues to crashes for said mods. The fact optifine is closed source makes it infinitely harder for these modders to pinpoint exactly what they could potentially do to fix the issues.

**Comment by TelepathicGrunt** [comment]
4.0.1 is out and sadly I had to switch to my old fragile mixin. I cannot use modifyArgs mixins in Forge because there's a bug with Forge and mixin that prevents modifyArgs from working. So I was using modifyArg instead and trying to do stuff to get the values I need into it. Turns out, they way I did that was not safe and was causing issues with rendering the correct height of honey fluids. 

So now it is using the old super fragile mixin that may or may not blow up with mods. Which has a side effect of not crashing Optifine. However, Optifine still make the honey fluid green in overworld and I will not be investigating that lol. 

Once Forge fixes modifyArgs mixins so I can use it, I'm switching back to it even though it crashes Optifine as the modifyArgs mixin is far safer for me to do in the long run. You can play with Optifine using this version of Bumblezone but it's time is limited as future versions will break with Optifine once the mixin bug in Forge is fixed.
